[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Makehuman for Omniverse"
description="MakeHuman Extension for Omniverse. Create and customize humans in your Omniverse scenes."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Services"

# Keywords for the extension
keywords = ["kit", "makehuman","human","character"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.asset_converter" = {}
"omni.kit.window.filepicker" = {}
"omni.anim.skelJoint" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "omni.makehuman"

# [python.pipapi]
# archiveDirs = ["../../mh/dist/makehuman-1.2.0-py3-none-any.whl"]

requirements = ["makehuman"]