[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

preview_image = ""

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/etc/icon.jpg"

# The title and description fields are primarily for displaying extension info in UI
title = "Makehuman for Omniverse"
description="MakeHuman Extension for Omniverse. Create and customize humans in your Omniverse scenes."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Services"

# Keywords for the extension
keywords = ["kit", "makehuman","human","character"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.asset_converter" = {}
"omni.kit.window.filepicker" = {}
"omni.anim.skelJoint" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "omni.makehuman"

[python.pipapi]
use_online_index = true

# Use this to specify a list of additional repositories if your pip package is hosted somewhere other
# than the default repo(s) configured in pip. Will pass these to pip with "--extra-index-url" argument
repositories = ["https://test.pypi.org/simple/"]

requirements = ["makehuman==1.2.2"]